/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAthleteDialog: typeof import('./src/components/AddAthleteDialog.vue')['default']
    AddCompetitionDialog: typeof import('./src/components/AddCompetitionDialog.vue')['default']
    CompetitionPlaces: typeof import('./src/components/CompetitionPlaces.vue')['default']
    CompetitionPlacesDropdown: typeof import('./src/components/CompetitionPlacesDropdown.vue')['default']
    copy: typeof import('./src/components/AddAthleteDialog copy.vue')['default']
    DeleteSportDialog: typeof import('./src/components/DeleteSportDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sports: typeof import('./src/components/Sports.vue')['default']
    SportsDropdown: typeof import('./src/components/SportsDropdown.vue')['default']
  }
}
